Project week 9, music releases - Elle Frankenberg & Isabella Markskog
Technigo/project-music-releases pull request #105
Opened 2021-03-12 15:39 UTC by IsabellaM5

**Link to our deployed project:**
https://dazzling-aryabhata-b33e50.netlify.app/ 

**Our reflections on how this week's project turned out:**
We did all the blue and red level requirements. 

This was the first week with React, which was a completely new concept for us. In the beginning, we struggled a bit with the different React concepts such as what a component is and how to use props. We tried to read the project brief and analyze how we needed to structure it all, but it wasn't until we had a late night team session that some things fell into place. After that, we got an idea on how to structure the components that enabled us to start coding. 

We're happy with how to project turned out! It was a fun project to start using React and that we started with a pair programming project. 

**Things we'd like to have clarified or explained in more detail:**
Not anything that we can think of at the moment regarding this project. We look forward to next project and dive deeper into the React world! 🐬🐬

2021-03-18 13:44 UTC, KarolCislowski requested changes
It is a great project. You need to adjust it to the smaller screens and it would be perfect. 🌈

2021-03-18 13:44 UTC, KarolCislowski commented on code/src/components/Album.js
> +          </div>
I can't see them on hover when I'm on 2 or 1 album per row width.

2021-03-18 13:44 UTC, KarolCislowski commented on code/src/components/Album.js
> +      <a className="album-name" href={props.albumLink}>{props.albumName}</a>
Both artist and album title section does not have a hover effect when I'm on 2 or 1 album per row width.

2021-03-18 13:44 UTC, KarolCislowski commented on code/src/components/Album.js
> +export const Album = (props) => {
When your album title is longer then 1 line it makes your album photo break the grid on top. Your photos should be in line and your text areas should be ready for longer text. 
![image](https://user-images.githubusercontent.com/50926159/111635072-69679500-87f7-11eb-83fc-87d48cc33b3b.png)

2021-03-18 13:44 UTC, KarolCislowski commented on code/src/components/Album.js
> +import { Artist } from './Artist'
There is a convention that says that we should divide outer dependencies (those located in node_modules) from local dependencies (all local files that we created - components, functions, data such as arrays) by one empty line. Moreover, style.css should be separated as well and located below local dependencies.

2021-03-22 14:32 UTC, IsabellaM5 commented
Hey Karol,

We have now made the requested changes to the code, see the recent push to the repo.

We had a follow up question regarding the hover effects. We placed them in the css-file so that they would only apply on the desktop view (breakpoint 1025 px) since we figured that hover effects are only visible on desktop and not mobile or tablet. Is it a convention then to place the css for hover effects on mobile breakpoint even though they are not visible? 😄

/Elle & Isabella 🐬🐬

2021-03-22 17:32 UTC, KarolCislowski approved these changes
Great Job 🦄

2021-10-10 16:46 UTC, closed without merging