Week 9 - Music Releases Project - Jamie and Tara
Technigo/project-music-releases pull request #86
Opened 2020-10-17 10:37 UTC by the-j-curl

Link to my deployed project:
https://jt-music.netlify.app/

My reflections on how this week's project turned out:
1) I enjoyed learning about React and creating a site using components. 
2) I feel that the basics were okay to grasp, but then when you start using props, maps etc it becomes more confusing and harder to follow.
3)  I would of liked a better understanding of React before moving on to the next project.
4) I managed to get some help from my team mates when I got stuck on displaying the different artist names

Things I'd like to have clarified or explained in more detail:
1) I would like a better understanding of NPM and how it works, and also what the package.json file does.
2) More clarification on props, map and their purpose
3) The cleanest way to structure components and their CSS

2020-10-26 10:09 UTC, EmOlsz requested changes
Well done project Jamie & Tara! Your code in general fulfils good practices.
Some things needs to be changed though - take a look on comments I left for you and provide changes. Hope they will help you in future projects :)

2020-10-26 10:09 UTC, EmOlsz commented on code/src/components/App.js
> +              key={album.name}
Over here you pass proper `key` value, good job :)

2020-10-26 10:09 UTC, EmOlsz commented on code/src/components/Artist.js
> +          if (props.index === 0) {
Well done!

2020-10-26 10:09 UTC, EmOlsz commented on code/src/index.css
> +  color: #ffffff;
`color: #fff`

2020-10-26 10:09 UTC, EmOlsz commented on code/src/index.js
> +const Write = () => {
Don't know what was the purpose of this component, but we shouldn't do things like that. We should pass `<App />` component directly into `ReactDOM.render()` method

2020-10-31 10:19 UTC, the-j-curl commented on code/src/components/Album.js
> +import { MusicIcons } from './MusicIcons'
Cool, thanks for explaining this Maks. 
Changes have been made as requested.

2020-11-02 12:43 UTC, EmOlsz approved these changes

2021-03-09 11:22 UTC, closed without merging